name: Test rcpputils
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-18.04]
    steps:
    - uses: ros-tooling/setup-ros@0.0.13
    - uses: ros-tooling/action-ros-ci@0.0.13
      with:
        package-name: rcpputils
    - uses: actions/upload-artifact@v2
      with:
        name: colcon-logs
        path: ros_ws/log
